const data = [
  [
    {eventName: 'DI', startInt: 4, endInt: 7},
    {eventName: 'SP', startInt: 5, endInt: 7},
    {eventName: 'PF', startInt: 2, endInt: 3},
    {eventName: 'JH', startInt: 1, endInt: 2},
    {eventName: 'BM', startInt: 3, endInt: 4},
    {eventName: 'MF', startInt: 0, endInt: 4},
    {eventName: 'JW', startInt: 0, endInt: 7},
    {eventName: 'CI', startInt: 0, endInt: 1},
    {eventName: 'SH', startInt: 3, endInt: 4},
    {eventName: 'DI', startInt: 4, endInt: 5},
    {eventName: 'BM', startInt: 4, endInt: 5},
    {eventName: 'ES', startInt: 2, endInt: 5},
    {eventName: 'CG', startInt: 2, endInt: 4},
    {eventName: 'CT', startInt: 4, endInt: 5},
    {eventName: 'BM', startInt: 6, endInt: 7},
    {eventName: 'AV', startInt: 4, endInt: 5},
    {eventName: 'PC', startInt: 0, endInt: 7},  
    {eventName: 'BM', startInt: 5, endInt: 6},
    {eventName: 'ES', startInt: 0, endInt: 2},
    {eventName: 'BM', startInt: 0, endInt: 1},
    {eventName: 'SH', startInt: 1, endInt: 2}
  ],
  [
    {eventName: 'PF', startInt: 2, endInt: 3},
    {eventName: 'JH', startInt: 1, endInt: 2},
    {eventName: 'JW', startInt: 0, endInt: 7},
    {eventName: 'KF', startInt: 0, endInt: 5},
    {eventName: 'SP', startInt: 6, endInt: 7},
    {eventName: 'CI', startInt: 0, endInt: 1},
    {eventName: 'SH', startInt: 3, endInt: 4},
    {eventName: 'DI', startInt: 4, endInt: 5},
    {eventName: 'BM', startInt: 4, endInt: 5},
    {eventName: 'AV', startInt: 4, endInt: 5},
    {eventName: 'SP', startInt: 2, endInt: 3},
    {eventName: 'PC', startInt: 0, endInt: 7},  
    {eventName: 'BM', startInt: 5, endInt: 6},
    {eventName: 'ES', startInt: 0, endInt: 2},
    {eventName: 'BM', startInt: 0, endInt: 1},
    {eventName: 'SH', startInt: 1, endInt: 2}
  ],
  [
    {eventName: 'PF', startInt: 2, endInt: 3},
    {eventName: 'JH', startInt: 1, endInt: 2},
    {eventName: 'BM', startInt: 3, endInt: 4},
    {eventName: 'MF', startInt: 0, endInt: 4},
    {eventName: 'KF', startInt: 0, endInt: 5},
    {eventName: 'SP', startInt: 6, endInt: 7},
    {eventName: 'DI', startInt: 4, endInt: 5},
    {eventName: 'BM', startInt: 4, endInt: 5},
    {eventName: 'ES', startInt: 2, endInt: 5},
    {eventName: 'CG', startInt: 2, endInt: 4},
    {eventName: 'CT', startInt: 4, endInt: 5},
    {eventName: 'AV', startInt: 4, endInt: 5},
    {eventName: 'SP', startInt: 2, endInt: 3},
    {eventName: 'PC', startInt: 0, endInt: 7},  
    {eventName: 'BM', startInt: 5, endInt: 6},
    {eventName: 'ES', startInt: 0, endInt: 2},
    {eventName: 'SH', startInt: 1, endInt: 2}
  ],
  [{eventName: 'SP', startInt: 5, endInt: 7},
    {eventName: 'PF', startInt: 2, endInt: 3},
    {eventName: 'MF', startInt: 0, endInt: 4},
    {eventName: 'JW', startInt: 0, endInt: 7},
    {eventName: 'KF', startInt: 0, endInt: 5},
    {eventName: 'SP', startInt: 6, endInt: 7},
    {eventName: 'DI', startInt: 4, endInt: 5}],
  [
    {eventName: 'SP', startInt: 5, endInt: 7},
    {eventName: 'PF', startInt: 2, endInt: 3},
    {eventName: 'MF', startInt: 0, endInt: 4},
    {eventName: 'JW', startInt: 0, endInt: 7},
    {eventName: 'KF', startInt: 0, endInt: 5},
    {eventName: 'SP', startInt: 6, endInt: 7},
    {eventName: 'DI', startInt: 4, endInt: 5},
    {eventName: 'BM', startInt: 4, endInt: 5},
    {eventName: 'ES', startInt: 2, endInt: 5},
    {eventName: 'CG', startInt: 2, endInt: 4},
    {eventName: 'CT', startInt: 4, endInt: 5},
    {eventName: 'BM', startInt: 6, endInt: 7},
    {eventName: 'ES', startInt: 0, endInt: 2},
    {eventName: 'BM', startInt: 0, endInt: 1},
    {eventName: 'SH', startInt: 1, endInt: 2}
  ]
]

export default data;